dist: bionic
sudo: required

language: python
python: "3.7"

services:
  - docker

install:
  - sudo pip install docker-compose

env:
  - DOCKER_COMPOSE_VERSION=1.25.0

before_install:
    - echo "$DOCKER_HUB_KEY" | docker login -u "$DOCKER_USERNAME" --password-stdin

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker tag whav/hav whav/hav:$TRAVIS_BUILD_NUMBER ;
      docker tag whav/hav whav/hav:$TRAVIS_COMMIT ;
      docker push whav/hav ;

      docker build -t whav/hav-cms:latest -t whav/hav-cms:$TRAVIS_BUILD_NUMBER -t whav/hav-cms:$TRAVIS_COMMIT -f frontend/cms/Dockerfile frontend/cms/;
      docker push whav/hav-cms ;

      docker build -t whav/hav-nginx:latest -t whav/hav-nginx:$TRAVIS_BUILD_NUMBER -t whav/hav-nginx:$TRAVIS_COMMIT -f Dockerfile.nginx . ;
      docker push whav/hav-nginx ;
    fi

script:
  - mkdir -p dist/incoming dist/archive dist/webassets dist/media
  - UG_IDS=`id -u`:`id -g` sed s/1000:1000/$UG_IDS/g <./env_files/docker.env >.env
  - cat .env
  - docker-compose config
  - docker-compose run django-asgi /venv/bin/pytest
