dist: xenial
sudo: required

language: python
python: "3.7"

install:
  - sudo pip install docker-compose

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin ;
      docker push whav/hav ;
      docker tag whav/hav whav/hav:$TRAVIS_BUILD_NUMBER ;
      docker push whav/hav:$TRAVIS_BUILD_NUMBER ;
      docker tag whav/hav whav/hav:$TRAVIS_COMMIT ;
      docker push whav/hav:$TRAVIS_COMMIT ;
      # also push nginx
      docker push whav/hav-nginx ;
      docker tag whav/hav-nginx whav/hav-nginx:$TRAVIS_BUILD_NUMBER ;
      docker push whav/hav-nginx:$TRAVIS_BUILD_NUMBER ;
      docker tag whav/hav-nginx whav/hav-nginx:$TRAVIS_COMMIT ;
      docker push whav/hav-nginx:$TRAVIS_COMMIT ;
    fi

script:
  - mkdir -p dist/incoming dist/archive dist/webassets
  - UG_IDS=`id -u`:`id -g` sed s/1000:1000/$UG_IDS/g <./env_files/docker.env >.env
  - cat .env
  - docker-compose config
  - docker-compose run django python manage.py test
