version: "3.7"

services:
    nginx:
        ports:
            - "8000:80"
    django-asgi:
        depends_on:
          - hav_db
          - whav_db
        environment:
          - DEBUG=True
        volumes:
          - ./backend:/hav/backend
        command: /venv/bin/python ./manage.py runserver 0.0.0.0:8000

    django-wsgi:
        depends_on:
        - hav_db
        - whav_db
        environment:
        - DEBUG=True
        volumes:
            - ./backend:/hav/backend
        command: /venv/bin/python ./manage.py runserver --noasgi 0.0.0.0:8000

    imaginary:
        ports:
            - "9000:9000"

    hav_db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=opensesame
            - POSTGRES_USER=hav
        expose:
            - 5432

    whav_db:
        image: mdillon/postgis:9.4
        environment:
            - POSTGRES_PASSWORD=opensesame
            - POSTGRES_USER=whav
        expose:
            - 5432


