version: "3.7"

x-django: &django
    build:
        context: .
    image: whav/hav:${TAG}
    user: ${DJANGO_UID}
    volumes:
        - ${HAV_ARCHIVE_ROOT}:/archive/hav/archive
        - ${INCOMING_FILES_ROOT}:/archive/hav/incoming
        - ${WEBASSETS_ROOT}:/archive/hav/webassets
        - /var/run/postgresql/.s.PGSQL.5432:/run/postgres/.s.PGSQL.5432
        - /run/redis/redis.sock:/run/redis/redis.sock
    environment:
        - IMAGINARY_SECRET=${IMAGINARY_SECRET}
        - IMAGINARY_URL_PREFIX=${IMAGINARY_URL_PREFIX}
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        - DATABASE_URL=${HAV_DATABASE_URL}
        - WHAV_DATABASE_URL=${WHAV_DATABASE_URL}
        - DEBUG=${DJANGO_DEBUG}
        - HAV_ARCHIVE_PATH=/archive/hav/archive
        - INCOMING_FILES_ROOT=/archive/hav/incoming
        - WEBASSET_ROOT=/archive/hav/webassets
        - CACHE_URL=${CACHE_URL}
        - SENTRY_DSN=${SENTRY_DSN}
        - RQ_SENTRY_DSN=${SENTRY_DSN}
    working_dir: /hav/backend
    depends_on:
        - redis

services:
    nginx:
        build:
            context: .
            dockerfile: ./Dockerfile.nginx
        image: whav/hav-nginx:${TAG}
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - thumbnail-cache:/www/cache
            - ${WEBASSETS_ROOT}:/www/webassets:ro
        depends_on:
            - django-asgi
            - django-wsgi
            - imaginary

    django-asgi:
        <<: *django

    django-wsgi:
        <<: *django
        command: [
          "uwsgi",
          "--module=hav.wsgi:application",
          "--master",
          "--socket=:8000"
          ]

    rq-archive:
        <<: *django
        user: ${ARCHIVE_UID}
        command: python manage.py rqworker archive

    rq-webassets:
        <<: *django
        user: ${WEBASSETS_UID}
        command: python manage.py rqworker webassets

    rq-default:
        <<: *django
        user: ${DJANGO_UID}
        command: python manage.py rqworker default

    imaginary:
        image: h2non/imaginary:1.0.18
        user: ${DJANGO_UID}
        environment:
            - URL_SIGNATURE_KEY=${IMAGINARY_SECRET}
            - VIPS_DISC_TRESHOLD=1g
        volumes:
            - ${HAV_ARCHIVE_ROOT}:/www/archive:ro
            - ${INCOMING_FILES_ROOT}:/www/incoming:ro
            - ${WEBASSETS_ROOT}:/www/webassets:ro
        command: -enable-url-source -mount /www -enable-url-signature -http-cache-ttl 31536000

    redis:
        image: redis
        volumes:
            - redis-data:/data
        expose:
            - 6379

volumes:
    redis-data:
    thumbnail-cache:
