version: '3'

services:

  hav_db:
    image: postgres
    hostname: ${HAV_DB_HOST}
    environment:
      - POSTGRES_PASSWORD=${HAV_DB_PW}
      - POSTGRES_USER=${HAV_DB_USER}
      - POSTGRES_DB=${HAV_DB_NAME}
    expose:
      - 5432
    volumes:
      - ./docker/mounts/db_dumps:/db_dumps:ro

  whav_db:
    image: mdillon/postgis:9.4
    hostname: ${HAV_DB_HOST}
    environment:
      - POSTGRES_PASSWORD=${WHAV_DB_PW}
      - POSTGRES_USER=${WHAV_DB_USER}
      - POSTGRES_DB=${WHAV_DB_NAME}
    expose:
      - 5432
    volumes:
      - ./docker/mounts/db_dumps:/db_dumps:ro

  django:
    depends_on:
      - "hav_db"
      - "whav_db"
      - "frontend"
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
      - ./dist:/dist
      - ./frontend/build:/build
      - ./docker/mounts/incoming:/incoming
    expose:
      - 8000


  caddy:
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./docker/caddy/Caddyfile:/etc/Caddyfile

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    expose:
      - 8000
    volumes:
      - ./frontend/:/code
    command: yarn run docker

  thumbor:
    image: apsl/thumbor:latest
    expose:
      - 8000
    volumes:
      - /data
      - ./dist/media:/data/loader
    environment:
      - LOADER=thumbor.loaders.file_loader_http_fallback
      - STORAGE=thumbor.storages.file_storage
      - AUTO_WEBP=True
      - FILE_STORAGE_ROOT_PATH=/data/storage
      - FILE_LOADER_ROOT_PATH=/data/loader
      - SECURITY_KEY=${THUMBOR_SECRET_KEY}
      - ALLOW_UNSAFE_URL=False

  redis:
    image: redis:alpine
    volumes:
      - ./docker/mounts/redis:/data

