version: "3"

services:
    django:
        ports:
            - "8000:8000"
        depends_on:
          - hav_db
          - whav_db
#        env_file:
#            - ../env_files/docker.env
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ../backend:/hav/backend
    hav_db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=opensesame
            - POSTGRES_USER=hav
        expose:
          - 5432

    whav_db:
        image: mdillon/postgis:9.4
        environment:
            - POSTGRES_PASSWORD=opensesame
            - POSTGRES_USER=whav
        expose:
          - 5432