version: "3.7"


x-django: &django
    build:
        context: .
    image: mcallis/hav
    user: "1000:1000"
    volumes:
        - ${ARCHIVE_ROOT}:/archive/hav/archive
        - ${INCOMING_FILES_ROOT}:/archive/hav/incoming
        - ${WEBASSETS_ROOT}:/archive/hav/webassets
        - /var/run/postgresql/.s.PGSQL.5432:/run/postgres/.s.PGSQL.5432
        - /run/redis/redis.sock:/run/redis/redis.sock
    environment:
        - IMAGINARY_SECRET=${IMAGINARY_SECRET}
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        - DEBUG=False
        - CACHE_URL=redis:///run/redis/redis.sock?db=1
        - DATABASE_URL=postgres://${DB_USER}@%2Frun%2Fpostgres/hav
        - WHAV_DATABASE_URL=postgres://${DB_USER}@%2Frun%2Fpostgres/whav
        - HAV_ARCHIVE_PATH=/archive/hav/archive
        - INCOMING_FILES_ROOT=/archive/hav/incoming
        - WEBASSET_ROOT=/archive/hav/webassets
        - IMAGESERVER_URL_PREFIX=/images/
    working_dir: /hav/backend

services:
    nginx:
        image: nginx:stable
        ports:
            - "127.0.0.1:8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./dist/nginx_cache:/tmp/nginx-thumbnails
            - ./dist/webassets:/www/webassets:ro
        depends_on:
            - django
            - imaginary

    django:
        <<: *django
        user: ${DJANGO_UID}
        command: daphne -p 8000 -b 0.0.0.0 hav.asgi:application

    rq-archive:
        <<: *django
        user: ${ARCHIVE_UID}
        command: python manage.py rqworker archive

    rq-webassets:
        <<: *django
        user: ${WEBASSETS_UID}
        command: python manage.py rqworker webassets

    rq-default:
        <<: *django
        user: ${DJANGO_UID}
        command: python manage.py rqworker default

    imaginary:
        image: h2non/imaginary:1.0.16
        user: ${DJANGO_UID}
        environment:
            - URL_SIGNATURE_KEY=bd!sdomqzg7dq51lsgdooh6li884c6s039ofd7!xd!0zg4wndc

        volumes:
            - ./dist/archive:/www/archive:ro
            - ./dist/incoming:/www/incoming:ro
            - ./dist/webassets:/www/webassets:ro
        command: -enable-url-source -mount /www -enable-url-signature -http-cache-ttl 31536000


