version: "3"

services:
    nginx:
        image: nginx:stable
        ports:
            - "80:80"
        volumes:
            - ../nginx.conf:/etc/nginx/nginx.conf:ro
            - ../dist/nginx_cache:/tmp/nginx-thumbnails
        depends_on:
            - django
            - imaginary

    django:
        build:
            context: ../
            dockerfile: Dockerfile
        image: hav_django
        env_file:
            - ../env_files/docker.env
        depends_on:
          - redis
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ../dist/archive:/archive/hav/archive
            - ../dist/incoming:/archive/hav/incoming
            - ../dist/webassets:/archive/hav/webassets

    redis:
        image: redis:4.0

    imaginary:
        build: https://github.com/h2non/imaginary.git
        env_file:
          - ../env_files/docker.env
        volumes:
            - ../dist/archive:/www/archive:ro
            - ../dist/incoming:/www/incoming:ro
            - ../dist/webassets:/www/webassets:ro
        command: -enable-url-source -mount /www -enable-url-signature -http-cache-ttl 31536000


