version: "3"
services:
  nginx:
    build:
      context: ./docker/nginx-imaginary
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - SECRET_SAUCE=TOPSECRET
    ports:
      - "9000:80"

  imaginary:
    image: h2non/imaginary:latest
    volumes:
      - ${INCOMING_FILES_ROOT}:/mnt/incoming:ro
      - ${HAV_ARCHIVE_PATH}:/mnt/archive:ro
    command: -enable-url-source -mount /mnt/