version: '2'

services:
  django:
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./:/code
      - ./dist:/dist
      - ./frontend/build:/build
      - ./docker/mounts/incoming:/incoming