version: "3"

volumes:
    archive:
        driver: local
        driver_opts:
            o: bind
            device: ../dist/archive
    incoming:
        driver: local
        driver_opts:
            o: bind
            device: ../dist/incoming
    webassets:
        driver: local
        driver_opts:
            o: bind
            device: ../dist/webassets
    imagecache:
        driver: local
        driver_opts:
            o: bind
            device: ../dist/imgcache

services:
    django:
        build:
            context: ../
        image: hav_django
        env_file:
            - ../env_files/docker.env
        command: ./manage.py runserver
        ports:
            - "8000:8000"
        depends_on:
          - hav_db
          - whav_db
          - redis
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ../dist/archive:/archive/hav/
            - ../dist/incoming:/archive/incoming
            - ../dist/webassets:/archive/webassets
    redis:
        image: redis:4.0

    hav_db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=opensesame
            - POSTGRES_USER=hav
        expose:
          - 5432

    whav_db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=opensesame
            - POSTGRES_USER=whav
        expose:
          - 5432




