version: "3"

services:
    django:
        ports:
            - "8000:8000"
        env_file:
            - ../env_files/docker.env
        volumes:
            - ../backend:/hav/backend
    hav_db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=opensesame
            - POSTGRES_USER=hav
        expose:
          - 5432

    whav_db:
        image: mdillon/postgis:9.4
        environment:
            - POSTGRES_PASSWORD=opensesame
            - POSTGRES_USER=whav
        expose:
          - 5432