version: "3"

services:
    django:
        build:
            context: ../
            dockerfile: Dockerfile.backend
        image: hav_django
        env_file:
            - ../env_files/docker.env
        ports:
            - "8000:8000"
        depends_on:
          - hav_db
          - whav_db
          - redis
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ../dist/archive:/archive/hav/
            - ../dist/incoming:/archive/incoming
            - ../dist/webassets:/archive/webassets

    redis:
        image: redis:4.0

    hav_db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=opensesame
            - POSTGRES_USER=hav
        expose:
          - 5432

    whav_db:
        image: mdillon/postgis:9.4
        environment:
            - POSTGRES_PASSWORD=opensesame
            - POSTGRES_USER=whav
        expose:
          - 5432

    imaginary:
        build: https://github.com/h2non/imaginary.git
        env_file:
          - ../env_files/docker.env
        volumes:
            - ../dist/archive:/www/archive:ro
            - ../dist/incoming:/www/incoming:ro
            - ../dist/webassets:/www/webassets:ro
        ports:
            - "9000:9000"
        command: -enable-url-source -mount /www -enable-url-signature -http-cache-ttl 31536000

volumes:
    archive:


